#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB26995E310250568 (lukasz@python.org)
#
Name     : black
Version  : 20.8b1
Release  : 9
URL      : https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz
Source0  : https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz
Source1  : https://files.pythonhosted.org/packages/dc/7b/5a6bbe89de849f28d7c109f5ea87b65afa5124ad615f3419e71beb29dc96/black-20.8b1.tar.gz.asc
Summary  : The uncompromising code formatter.
Group    : Development/Tools
License  : MIT Python-2.0
Requires: black-bin = %{version}-%{release}
Requires: black-license = %{version}-%{release}
Requires: black-python = %{version}-%{release}
Requires: black-python3 = %{version}-%{release}
Requires: aiohttp
Requires: aiohttp-cors
Requires: appdirs
Requires: click
Requires: colorama
Requires: dataclasses
Requires: mypy_extensions
Requires: pathspec
Requires: regex
Requires: toml
Requires: typed_ast
Requires: typing_extensions
BuildRequires : aiohttp
BuildRequires : aiohttp-cors
BuildRequires : appdirs
BuildRequires : buildreq-distutils3
BuildRequires : click
BuildRequires : colorama
BuildRequires : dataclasses
BuildRequires : mypy_extensions
BuildRequires : pathspec
BuildRequires : regex
BuildRequires : setuptools
BuildRequires : setuptools_scm-python
BuildRequires : toml
BuildRequires : typed_ast
BuildRequires : typing_extensions

%description
<h2 align="center">The Uncompromising Code Formatter</h2>
        
        <p align="center">

%package bin
Summary: bin components for the black package.
Group: Binaries
Requires: black-license = %{version}-%{release}

%description bin
bin components for the black package.


%package license
Summary: license components for the black package.
Group: Default

%description license
license components for the black package.


%package python
Summary: python components for the black package.
Group: Default
Requires: black-python3 = %{version}-%{release}

%description python
python components for the black package.


%package python3
Summary: python3 components for the black package.
Group: Default
Requires: python3-core
Provides: pypi(black)
Requires: pypi(aiohttp)
Requires: pypi(aiohttp_cors)
Requires: pypi(appdirs)
Requires: pypi(click)
Requires: pypi(mypy_extensions)
Requires: pypi(pathspec)
Requires: pypi(regex)
Requires: pypi(toml)
Requires: pypi(typed_ast)
Requires: pypi(typing_extensions)

%description python3
python3 components for the black package.


%prep
%setup -q -n black-20.8b1
cd %{_builddir}/black-20.8b1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605207300
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/black
cp %{_builddir}/black-20.8b1/LICENSE %{buildroot}/usr/share/package-licenses/black/edd079e7a759fe1fcf1d089e28b9c7df2080b42c
cp %{_builddir}/black-20.8b1/docs/_static/license.svg %{buildroot}/usr/share/package-licenses/black/748f560ab176347fcb653c766cb3b5f91d99b4fd
cp %{_builddir}/black-20.8b1/src/blib2to3/LICENSE %{buildroot}/usr/share/package-licenses/black/8482348f12824b36fba59883f9dd7fe03c1f86ca
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/black
/usr/bin/black-primer
/usr/bin/blackd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/black/748f560ab176347fcb653c766cb3b5f91d99b4fd
/usr/share/package-licenses/black/8482348f12824b36fba59883f9dd7fe03c1f86ca
/usr/share/package-licenses/black/edd079e7a759fe1fcf1d089e28b9c7df2080b42c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
