#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : black
Version  : 21.11b1
Release  : 31
URL      : https://files.pythonhosted.org/packages/73/df/5a4c5af64a25212d494b31d7b62f8212424c0c8ffdac9462a7d15bc17b9f/black-21.11b1.tar.gz
Source0  : https://files.pythonhosted.org/packages/73/df/5a4c5af64a25212d494b31d7b62f8212424c0c8ffdac9462a7d15bc17b9f/black-21.11b1.tar.gz
Summary  : The uncompromising code formatter.
Group    : Development/Tools
License  : MIT Python-2.0
Requires: black-bin = %{version}-%{release}
Requires: black-license = %{version}-%{release}
Requires: black-python = %{version}-%{release}
Requires: black-python3 = %{version}-%{release}
Requires: typed_ast
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pypi(click)
BuildRequires : pypi(mypy_extensions)
BuildRequires : pypi(myst_parser)
BuildRequires : pypi(pathspec)
BuildRequires : pypi(platformdirs)
BuildRequires : pypi(regex)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(sphinx_copybutton)
BuildRequires : pypi(sphinxcontrib_programoutput)
BuildRequires : pypi(tomli)
BuildRequires : pypi(typing_extensions)
BuildRequires : pypi(wheel)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : typed_ast
BuildRequires : virtualenv

%description
A subset of lib2to3 taken from Python 3.7.0b2.
Commit hash: 9c17e3a1987004b8bcfbe423953aad84493a7984

%package bin
Summary: bin components for the black package.
Group: Binaries
Requires: black-license = %{version}-%{release}

%description bin
bin components for the black package.


%package license
Summary: license components for the black package.
Group: Default

%description license
license components for the black package.


%package python
Summary: python components for the black package.
Group: Default
Requires: black-python3 = %{version}-%{release}

%description python
python components for the black package.


%package python3
Summary: python3 components for the black package.
Group: Default
Requires: python3-core
Provides: pypi(black)
Requires: pypi(aiohttp)
Requires: pypi(aiohttp_cors)
Requires: pypi(click)
Requires: pypi(mypy_extensions)
Requires: pypi(myst_parser)
Requires: pypi(pathspec)
Requires: pypi(platformdirs)
Requires: pypi(regex)
Requires: pypi(sphinx)
Requires: pypi(sphinx_copybutton)
Requires: pypi(sphinxcontrib_programoutput)
Requires: pypi(tomli)
Requires: pypi(typing_extensions)

%description python3
python3 components for the black package.


%prep
%setup -q -n black-21.11b1
cd %{_builddir}/black-21.11b1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637366317
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/black
cp %{_builddir}/black-21.11b1/LICENSE %{buildroot}/usr/share/package-licenses/black/edd079e7a759fe1fcf1d089e28b9c7df2080b42c
cp %{_builddir}/black-21.11b1/docs/_static/license.svg %{buildroot}/usr/share/package-licenses/black/e71d25df55070a88d192a9ecf3a7ad755e44e8ee
cp %{_builddir}/black-21.11b1/src/blib2to3/LICENSE %{buildroot}/usr/share/package-licenses/black/8482348f12824b36fba59883f9dd7fe03c1f86ca
python3 -m install --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/black
/usr/bin/black-primer
/usr/bin/blackd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/black/8482348f12824b36fba59883f9dd7fe03c1f86ca
/usr/share/package-licenses/black/e71d25df55070a88d192a9ecf3a7ad755e44e8ee
/usr/share/package-licenses/black/edd079e7a759fe1fcf1d089e28b9c7df2080b42c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
